version: '3'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    networks:
      gocod:
        ipv4_address: 172.30.0.3
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      gocod:
        ipv4_address: 172.30.0.4
networks:
  gocod:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1